/**
 * Default settings values for Claude Memory
 * Shared across UI components and hooks
 */
export const DEFAULT_SETTINGS = {
  CLAUDE_MEM_MODEL: 'claude-sonnet-4-6',
  CLAUDE_MEM_CONTEXT_OBSERVATIONS: '50',
  CLAUDE_MEM_WORKER_PORT: '37777',
  CLAUDE_MEM_WORKER_HOST: '127.0.0.1',

  // AI Provider Configuration
  CLAUDE_MEM_PROVIDER: 'claude',
  CLAUDE_MEM_GEMINI_API_KEY: '',
  CLAUDE_MEM_GEMINI_MODEL: 'gemini-2.5-flash-lite',
  CLAUDE_MEM_OPENROUTER_API_KEY: '',
  CLAUDE_MEM_OPENROUTER_MODEL: 'xiaomi/mimo-v2-flash:free',
  CLAUDE_MEM_OPENROUTER_SITE_URL: '',
  CLAUDE_MEM_OPENROUTER_APP_NAME: 'claude-mem',
  CLAUDE_MEM_GEMINI_RATE_LIMITING_ENABLED: 'true',
  CLAUDE_MEM_LOCAL_BASE_URL: '',
  CLAUDE_MEM_LOCAL_MODEL: '',
  CLAUDE_MEM_LOCAL_API_KEY: '',
  CLAUDE_MEM_LOCAL_MAX_TOKENS: 'auto',
  CLAUDE_MEM_LOCAL_MAX_CONTEXT_MESSAGES: '20',
  CLAUDE_MEM_LOCAL_MAX_CONCURRENT: '1',
  CLAUDE_MEM_LOCAL_FALLBACK_ENABLED: 'false',
  CLAUDE_MEM_LOCAL_REQUEST_TIMEOUT_MS: '300000',
  CLAUDE_MEM_LOCAL_ENABLE_THINKING: 'false',
  CLAUDE_MEM_LOCAL_TEMPERATURE: '0.7',
  CLAUDE_MEM_LOCAL_TOP_P: '0.8',
  CLAUDE_MEM_LOCAL_TOP_K: '20',
  CLAUDE_MEM_LOCAL_MIN_P: '0.0',
  CLAUDE_MEM_LOCAL_PRESENCE_PENALTY: '1.5',
  CLAUDE_MEM_LOCAL_REPETITION_PENALTY: '1.0',
  CLAUDE_MEM_LOCAL_MAX_OUTPUT_TOKENS: '4096',

  // Token Economics — match SettingsDefaultsManager defaults (off by default to keep context lean)
  CLAUDE_MEM_CONTEXT_SHOW_READ_TOKENS: 'false',
  CLAUDE_MEM_CONTEXT_SHOW_WORK_TOKENS: 'false',
  CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT: 'false',
  CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_PERCENT: 'true',

  // Display Configuration — match SettingsDefaultsManager defaults
  CLAUDE_MEM_CONTEXT_FULL_COUNT: '0',
  CLAUDE_MEM_CONTEXT_FULL_FIELD: 'narrative',
  CLAUDE_MEM_CONTEXT_SESSION_COUNT: '10',

  // Feature Toggles
  CLAUDE_MEM_CONTEXT_SHOW_LAST_SUMMARY: 'true',
  CLAUDE_MEM_CONTEXT_SHOW_LAST_MESSAGE: 'false',

  // Exclusion Settings
  CLAUDE_MEM_EXCLUDED_PROJECTS: '',
  CLAUDE_MEM_FOLDER_MD_EXCLUDE: '[]',
} as const;
